### ISSUE TITLE
Doesn't work with webrtc-adapter

### ISSUE THREAD

**Issue by josch** [andrewrk/browserify-lite#11]
When using browserify-lite with webrtc-adapter, the following error is generated:

```
$ browserify-lite ./src/js/adapter_core.js --outfile adapter.js --standalone adapter
/usr/lib/nodejs/browserify-lite/cli.js:29
  if (err) throw err;
           ^

Error: module ) in /tmp/webrtc-adapter/node-webrtc-adapter-4.1.0/src/js/chrome not found
    at trySearchPath (/usr/lib/nodejs/browserify-lite/index.js:257:32)
    at /usr/lib/nodejs/browserify-lite/index.js:262:7
    at /usr/lib/nodejs/browserify-lite/index.js:282:21
    at FSReqWrap.oncomplete (fs.js:82:15)
```

This suggests that somehow `)` is parsed as a package name somewhere. Maybe the fix is simple?

**Comment by josch** [comment]
Turns out that this error only occurs with browserify-lite 0.3.0 but is fixed with 0.5.0.
